# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mogcli < Formula
  desc "Microsoft 365 in your terminal"
  homepage "https://github.com/jaredpalmer/mogcli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaredpalmer/mogcli/releases/download/v0.0.1/mogcli_0.0.1_darwin_amd64.tar.gz"
      sha256 "cf03648fccd2d91ab9a85960bf5e931142db42e54ce47eb152560a3c11667020"

      def install
        bin.install "mog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaredpalmer/mogcli/releases/download/v0.0.1/mogcli_0.0.1_darwin_arm64.tar.gz"
      sha256 "b7124959eb2dca68074f54b9c0475febf2d897f1b8bd28c7a415d7dd1144560e"

      def install
        bin.install "mog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredpalmer/mogcli/releases/download/v0.0.1/mogcli_0.0.1_linux_amd64.tar.gz"
      sha256 "44fea74d3c6a2fbffbf0f1c95545ee43c8368fc19a930ec4f990fd60a275265c"
      def install
        bin.install "mog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredpalmer/mogcli/releases/download/v0.0.1/mogcli_0.0.1_linux_arm64.tar.gz"
      sha256 "4833180b27e901f7fa88f29bc5644a575c1d19407953a7901947a329b271de2a"
      def install
        bin.install "mog"
      end
    end
  end

  test do
    system "#{bin}/mog", "--help"
  end
end
